Fix Jenkins job YAML specification for e2e tests
The `--prometheus` flag needs to come after the package name, or the job
fails with the following error:
"build .: cannot find module for path ."

Also fix test/e2e/infra/vagrant/push_antrea.sh script for macOS.