remove vet
`go vet ./...` will fail and report below error:
```
../../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.1/pkg/internal/testing/controlplane/plane.go:195:14: undefined: os.CreateTemp
note: module requires Go 1.16
```

we can use the same lint tools as antrea and enable in the future
so remove it for now, so we can run `make build` correctly.

Signed-off-by: Lan Luo <luola@vmware.com>